import { buildPdfDocument, clampText, formatCurrency, normalizeDate, safeArray } from "../utils.js";

const buildProposalParagraphs = (payload) => {
  const eventDate = normalizeDate(payload.eventDate);
  const budget = payload.budget ? formatCurrency(payload.budget) : "to be finalized";

  return [
    `This proposal is submitted on behalf of the ${payload.clubName} for the event "${payload.eventTitle}". The event is planned for ${eventDate} at ${payload.venue || "the proposed venue"}.`,
    `The core objective is to ${clampText(payload.objective || "deliver a high-value event experience")}. The event summary provided by the organizer is: ${clampText(payload.eventSummary || payload.description || "No summary provided.")}`,
    `We request approval and administrative support for logistics, communication, and venue coordination. The tentative budget is ${budget}. The proposed audience includes ${clampText(payload.targetAudience || "students, faculty, and invited guests")}.`,
    `The event will be executed by the ${payload.clubName || "organizing club"} with support from the relevant faculty coordinators and student volunteers. We assure compliance with institutional policies and proper post-event documentation.`,
  ];
};

const buildReportParagraphs = (payload) => {
  const attendeeLine = payload.totalAttendees
    ? `${payload.totalAttendees} attendees participated`
    : "attendance details will be finalized by the organizing team";
  const budgetLine = payload.actualSpend
    ? `The final spend was ${formatCurrency(payload.actualSpend)} against an approved estimate of ${formatCurrency(payload.totalBudget || payload.actualSpend)}.`
    : "The final financial reconciliation is in progress.";

  return [
    `This report summarizes the event "${payload.eventTitle}" organized by the ${payload.clubName} on ${normalizeDate(payload.eventDate)} at ${payload.venue || "the designated venue"}.`,
    `Based on the inputs submitted, ${attendeeLine}. The event focus included ${clampText(payload.eventSummary || "knowledge sharing, engagement, and structured execution")}.`,
    `${budgetLine} The organizing team tracked the event through planned activities, participant engagement, and operational checkpoints.`,
    `Major outcomes include ${clampText(payload.outcomes || "successful execution, audience participation, and completion of the planned agenda")}. Supporting photographs and highlights have been included separately for archival and review purposes.`,
  ];
};

export const generateProposalDocument = async (payload) => {
  const pdfBuffer = await buildPdfDocument({
    title: "Event Proposal",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Proposal",
    date: payload.date || payload.eventDate,
    subject: payload.subject || `Proposal for ${payload.eventTitle || "Event"}`,
    addressedTo: payload.authorityName,
    clubName: payload.clubName,
    bodyParagraphs: buildProposalParagraphs(payload),
    highlights: safeArray(payload.keyPoints),
    footerText: "Generated by DocuPrint Proposal Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
  });

  return {
    fileName: `${(payload.eventTitle || "event-proposal").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventTitle,
      clubName: payload.clubName,
      authorityName: payload.authorityName,
      estimatedBudget: payload.budget ? formatCurrency(payload.budget) : null,
    },
    pdfBuffer,
  };
};

export const generateReportDocument = async (payload) => {
  const analytics = [
    payload.totalAttendees ? `Participants recorded: ${payload.totalAttendees}` : null,
    payload.feedbackScore ? `Average feedback score: ${payload.feedbackScore}/10` : null,
    payload.totalBudget ? `Approved budget: ${formatCurrency(payload.totalBudget)}` : null,
    payload.actualSpend ? `Actual spend: ${formatCurrency(payload.actualSpend)}` : null,
  ].filter(Boolean);

  const pdfBuffer = await buildPdfDocument({
    title: "Event Report",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Report",
    date: payload.date || payload.eventDate,
    subject: payload.subject || `Report for ${payload.eventTitle || "Event"}`,
    addressedTo: payload.authorityName,
    clubName: payload.clubName,
    bodyParagraphs: buildReportParagraphs(payload),
    highlights: safeArray(payload.keyHighlights),
    analytics,
    footerText: "Generated by DocuPrint Reporting Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
  });

  return {
    fileName: `${(payload.eventTitle || "event-report").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventTitle,
      totalAttendees: payload.totalAttendees || null,
      actualSpend: payload.actualSpend ? formatCurrency(payload.actualSpend) : null,
      keyHighlights: safeArray(payload.keyHighlights),
    },
    pdfBuffer,
  };
};
